sheep:
  #此项目设置为false后，取消关卡硬编码
  hard-code: false

#用户自定义信息尚未实现
user:
  uid: 114514
  nickname: 薯条
  avatar: baidu.com

#话题设置
#id与name对照如下，name可以自定义但不保证字库支持
###
# 1-僵尸#道士
# 2-狼人#吸血鬼
# 3-黑羊#白羊
# 4-五仁#莲蓉
# 5-学生#老师
# 6-嫦娥#玉兔
# 7-学童#夫子
###
topic:
  id: 6
  name: 嫦娥#玉兔